### ISSUE TITLE
默认admin的密码是什么？

### ISSUE THREAD

**Issue by xianyo** [johnjerome/ThinkAdmin#1]
你好，请问默认admin的密码是什么？

**Comment by meegle** [comment]
123456

**Comment by chenbk85** [comment]
你好,请问 http://localhost/ThinkAdmin/index.php/admin/index/index.html 返回 404 Not Found 是什么原因呢谢谢

**Comment by meegle** [comment]
怀疑是你的运行容器不支持url的pathinfo模式。
你可以尝试用url的普通模式访问。具体配置如下：

> 在App/Common/Conf/config.php中找到 <code>'URL_MODEL' => 1</code> 改为 <code>'URL_MODEL' => 0</code> 。

**Comment by chenbk85** [comment]
ths
